menu:
    首页: /
    文章: /archives/
    关于: /about/

favicon: /favicon.ico
logo: https://avatars1.githubusercontent.com/u/3142935?v=3&s=466 or file
motto: asd
# Comment
# e.g disqus: helloworld
disqus:
duoshuo:

# Analytics
# google-analytics:
ga: UA-147983033-1

# Copyright Infomation
startyear: 2016

# Styles shoule be found in the list: https://highlightjs.org/static/demo/
# use the lowercase letters and replace space with -
codestyle: monokai
